name: phpunit

on:
    push:
        branches:
            - 1.x
            - 2.x
    pull_request:

jobs:
    phpunit:
        strategy:
            matrix:
                php: ['8.1', '8.2', '8.3', '8.4']

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: intl
                    coverage: pcov
            -   name: Install dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: ${{ matrix.php == '8.4' && '--ignore-platform-req=php' || '' }}
            -   name: Run phpunit
                run: vendor/bin/phpunit --colors=always --coverage-text
