name: psalm

on:
    push:
        branches:
            - 1.x
            - 2.x
    pull_request:

jobs:
    psalm:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    extensions: intl
                    coverage: none
            -   name: Install dependencies
                uses: ramsey/composer-install@v1
            -   name: Run psalm
                run: vendor/bin/psalm --shepherd --output-format=github
